### ISSUE TITLE
Tanks don't fill completely when stacked with different upgrades

### ISSUE THREAD

**Issue by Sempiternity87** [Indemnity83/irontank#10] opened 2015-09-28 05:12 UTC
When stacking tanks of different types, and adding liquid to the top tank, WAILA shows the full volumn, but the tank fills before it gets there.
![2015-09-27_22 03 54](https://cloud.githubusercontent.com/assets/2977023/10128217/56afed6a-6564-11e5-86a2-0d250aa6c406.png)
![2015-09-27_22 04 02](https://cloud.githubusercontent.com/assets/2977023/10128214/56af0b20-6564-11e5-9325-0a94f785c177.png)
![2015-09-27_22 04 04](https://cloud.githubusercontent.com/assets/2977023/10128215/56af209c-6564-11e5-96b6-1c220d879e79.png)
![2015-09-27_22 04 06](https://cloud.githubusercontent.com/assets/2977023/10128219/56b34492-6564-11e5-990a-852da4da8af9.png)
![2015-09-27_22 04 07](https://cloud.githubusercontent.com/assets/2977023/10128218/56b1084e-6564-11e5-8c01-d51d56fe278a.png)
![2015-09-27_22 04 09](https://cloud.githubusercontent.com/assets/2977023/10128216/56af3cbc-6564-11e5-8131-d6cc1da58849.png)
![2015-09-27_22 04 10](https://cloud.githubusercontent.com/assets/2977023/10128222/56c16ad6-6564-11e5-86c4-e928edabccd1.png)
![2015-09-27_22 04 12](https://cloud.githubusercontent.com/assets/2977023/10128220/56bf1452-6564-11e5-8a79-31a2fb405c96.png)
![2015-09-27_22 04 16](https://cloud.githubusercontent.com/assets/2977023/10128221/56c12e90-6564-11e5-802b-95bd733628e2.png)
![2015-09-27_22 04 17](https://cloud.githubusercontent.com/assets/2977023/10128224/56c3338e-6564-11e5-98b4-886e75a79a66.png)
![2015-09-27_22 04 19](https://cloud.githubusercontent.com/assets/2977023/10128223/56c2e33e-6564-11e5-874b-48bac3dbe521.png)
![2015-09-27_22 04 20](https://cloud.githubusercontent.com/assets/2977023/10128225/56c5a7ea-6564-11e5-9dc6-3b36c062dcfd.png)
![2015-09-27_22 04 22](https://cloud.githubusercontent.com/assets/2977023/10128227/56d1d4e8-6564-11e5-88db-f858f08ca945.png)
![2015-09-27_22 04 23](https://cloud.githubusercontent.com/assets/2977023/10128229/56d57710-6564-11e5-83b4-b40bd8fd4517.png)
![2015-09-27_22 04 25](https://cloud.githubusercontent.com/assets/2977023/10128226/56d1cb6a-6564-11e5-91b0-d029d0899b37.png)
![2015-09-27_22 04 26](https://cloud.githubusercontent.com/assets/2977023/10128230/56d6028e-6564-11e5-84de-1650386d716d.png)
![2015-09-27_22 04 27](https://cloud.githubusercontent.com/assets/2977023/10128228/56d510ea-6564-11e5-9658-429eff9f1f06.png)
![2015-09-27_22 04 31](https://cloud.githubusercontent.com/assets/2977023/10128231/56d8fc0a-6564-11e5-9a31-2d04080e159c.png)
![2015-09-27_22 04 34](https://cloud.githubusercontent.com/assets/2977023/10128232/56e29382-6564-11e5-9f5d-de28ec70af17.png)
![2015-09-27_22 04 36](https://cloud.githubusercontent.com/assets/2977023/10128233/56e4b036-6564-11e5-8a0c-f7cff9d3c9ca.png)
![2015-09-27_22 04 38](https://cloud.githubusercontent.com/assets/2977023/10128234/56e797a6-6564-11e5-95c6-2793b090cc2e.png)
![2015-09-27_22 04 39](https://cloud.githubusercontent.com/assets/2977023/10128235/56e816cc-6564-11e5-97d2-0715b9e9bdf0.png)
![2015-09-27_22 04 41](https://cloud.githubusercontent.com/assets/2977023/10128236/56e8b05a-6564-11e5-9b0b-d9ec5a3a145f.png)

**Comment by Indemnity83** [comment] 2015-09-28 07:09
WAILA is wrong on the total capacity, the first number (filled amount) is correctly the total capacity of the tanks in every one of your screenshots. 

This is a duplicate of #6

**Closed as completed by Indemnity83** 2015-09-28 07:09 UTC
Labels: resolution: duplicate
