### ISSUE TITLE
Tank Modules

### ISSUE THREAD

**Issue by Sempiternity87** [Indemnity83/irontank#32] opened 2017-07-17 18:26 UTC
Have modules for doing more specific/automated tasks. There could be one for pulling a target liquid, one for voiding any extra liquid, maybe one to output a redstone signal based on the capacity filled/remaining.

**Comment by Indemnity83** [comment] 2017-07-17 19:06
Isn't this a duplicate of #23

**Closed as completed** 2017-07-17 19:06 UTC
