### ISSUE TITLE
Gold to diamond tank upgrade produces gold to diamond chest upgrade

### ISSUE THREAD

**Issue by Ghent** [Indemnity83/irontank#52] opened 2018-02-04 17:29 UTC
I'm putting in the materials to craft a gold to diamond tank upgrade, but when I do, the crafting table shows that it produces a gold to diamond chest upgrade.

This is in 2.1.0-beta.4

**Comment by Indemnity83** [comment] 2018-02-04 18:52
Duplicate of #50

**Closed as completed by Indemnity83** 2018-02-04 18:52 UTC
